### ISSUE TITLE
Moodle Overflow when deleted automatically duplicates itself on a periodic basis

### ISSUE THREAD

**Issue by Fae6068123** [learnweb/moodle-mod_moodleoverflow#79] opened 2021-05-13 08:55 UTC
When Deleting the plugin, and once the plugin is in the Recycle box, every time the cron job is run, the plugin is automatically duplicating itself on a periodic basis of around 15 to 20 mins. As a result of this issue, users will see multiple instances or copies of the same task in the recycle bin. In a test conducted yesterday, the plugin was able to automatically duplicate itself 4 times before the 1 hour time frame expired. For longer time periods, it will appear in recycle bin more times.

**Comment by justusdieckmann** [comment] 2021-05-26 15:40
Hey,

thank you for the issue. I think this behaviour is caused by a bug that was already fixed by #73.

Could you check if the problem resolves if you update to the latest moodleoverflow release (`v3.11-r1`)? (The moodleoverflow instance might be added to the recycling bin one last time after the update).

Please reopen the issue, if the bug still occurs :)

Cheers
Justus

**Closed by justusdieckmann** 2021-05-26 15:40 UTC
